### ISSUE TITLE
Bug: setup command produces a broken mocha configuration

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#30]
`appmap.yml` has to be manually updated after the setup wizard creates it in order for the mocha test recording to work:

Working option 1:
```yaml
app: MyApp
recorder: mocha
mode: local
scenario: my-scenario
scenarios:
  my-scenario:
    type: spawn
    exec: mocha
    argv: [-r, ts-node/register, -r, source-map-support/register, --recursive, test/server/**/*.ts]
output:
  directory: tmp/appmap
hooks:
  esm: true
  cjs: true
  http: true
  mysql: false
  pg: false
  sqlite3: false
ordering: causal
pruning: true
log: info
```

Working option 2:
```yaml
app: MyApp
recorder: mocha
mode: local
scenario: my-scenario
scenarios:
  my-scenario: [mocha, -r, ts-node/register, -r, source-map-support/register, --recursive, test/server/**/*.ts]
output:
  directory: tmp/appmap
hooks:
  esm: true
  cjs: true
  http: true
  mysql: false
  pg: false
  sqlite3: false
ordering: causal
pruning: false
log: info 
```
