### ISSUE TITLE
Bug: Collection of paths in appmap.yml is not restricting code objects in recorded appmaps

### ISSUE THREAD

**Issue by ptrdvrk** [applandinc/appmap-agent-js#44]
Example: appmap.yml
```yaml
name: Hugo
packages:
  - path: lib
  - path: models
  - path: routes
  - path: data
```
[Recorded AppMap](https://github.com/applandinc/appmap-agent-js/files/7498333/juice-shop.fileUpload.appmap.copy.json.txt)
